create database casestudy1;
use casestudy1;

select * from product;
select * from location;
select  * from fact;

select 
       COUNT(*) as totalrows
from fact;

--1)  Display the number of states present in theLocationTable.
select 
       distinct state as number_of_states_present
from Location;

--2) Howmany products are of regular type?
select * from Product;

select
       COUNT(*) as total_product_regular
from Product 
where Type='regular'

 ---3)Howmuch spending has been done on marketing of product ID1?
 select * from fact;

select 
        SUM(marketing) as total_sum_on_marketing
from fact 
where ProductId=1

--4)  What is the minimum sales of a product?
select 
       productid,
       MIN(sales) as min_sales_by_product
from fact 
group by productid

--5) Display the max Cost of Good Sold (COGS).
select 
       MAX(cogs) as max_cost_goods_sold
from fact 

---6) 6. Display the details of the product where product type iscoffee.
select * from Product;
select 
       product,
       TYPE 
from Product
where Product_Type='coffee'

--7)  Display the details where total expenses are greater than40.
select * from fact 
select 
       * 
from fact 
where Total_Expenses > 40

--8) . What is the average sales in area code 719?
select 
       AVG(sales) as avg_sales_code719
from fact
where Area_Code= 719

--9)  Find out the total profit generated by Colorado state.
select 
       SUM(f.profit) as total_profit_colorado
from fact f
inner join Location l
on f.Area_Code = l.Area_Code
where l.state='colorado'


select * from Location;

--10) Display the average inventory for each product ID.
select 
        productid,
        AVG(inventory) as avg_inventory_by_product
from fact 
group by productid

--11) Display state in a sequential order in a LocationTable.
select
       state as State_in_asc 
from location
order by state

---12) Display the average budget of the Product where the average budget
--margin should be greater than 100.-------(doubt)

select *  from fact  

select 
        productid,
        AVG(budget_margin) over () as avg_budget_margin
from fact
where budget_margin>100

--13) What is the total sales done on date 2010-01-01?
 select  * from fact 
 select 
         SUM(sales) as total_sales
 from fact  
 where Date='2010-01-01'

 --14) Display the average total expense of each product ID on anindividual date.
select 
       Date ,
       productid,
       AVG(total_expenses) as total_avg_expenses
from fact 
group by productid ,
Date 

--15)  Display the table with the following attributes such as date, 
--productID,product_type, product, sales, profit, state, area_code.
 
 select * from Product
 select * from fact 
 select * from Location 

 select 
        f.DATE ,
        f.productid,
        p.Product_type ,
        p.Product,
        f.sales ,
        f.profit ,
        l.state ,
        l.area_code 
from fact f
left join Product p
on f.ProductId=p.ProductId
left join Location l
on f.Area_Code=l.Area_Code 

--16)  Display the rank without any gap to show the sales wiserank.
select 
        sales ,
        dense_RANK() over(order by sales desc) as sales_rank
from fact 

--17) Find the state wise profit and sales.
select 
       l.state,
       sum(f.profit) [total profit],
       sum(f.sales) [total sales]
from location l
left join fact f
on l.area_code=f.area_code
group by l.state
 
----18) Find the state wise profit and sales along with the productname.
select 
       l.State,
       p.product  as Productname,
       sum(f.profit) [total profit],
       sum(f.sales) [total sales]
from location l
left join fact f
on l.area_code=f.area_code
left join Product p
on p.ProductId=f.productid
group by l.state,p.product 

19)If there is an increase in sales of 5%, calculate the 
increasedsales.
select 
      sales,
      sales * 105 /100 as increased_sales
from fact 

20)Find the maximum profit along with the product ID and 
producttype.

select 
      product.productid,
      product.product_type,
      MAX(fact.profit) as max_profit
from product 
left join fact
on fact.ProductId=Product.productid
group by product.ProductId,product.product_type


select * from Product
select * from fact 

21) Create a stored procedure to fetch the result according to 
theproduct type from ProductTable.

create procedure getproductsummary as 
begin 
      select 
             Product_type 
      from  Product
      group by product_type
end 
exec getproductsummary;

22)Write a query by creating a condition in which if the total 
expenses isless than 60 then it is a profit or else loss
select * from fact
select 
       total_expenses,
       case
            when total_expenses < 60 then 'profit'
            else 'loss'
        end as category
        from fact







